import type { Snapshot } from "./types";
const timeline = (last: string) => [
  { label: "Submitted", time: "12:18:37" },
  { label: "Admitted", time: "+1.8s" },
  { label: "Scheduled · ben3", time: "+0.4s" },
  { label: last, time: "12:18:40" },
];
const feeds = {
  worker: [
    {
      id: "f5",
      at: "12:18:43",
      kind: "tool",
      message: "Checks returned 6 / 6 passing",
    },
    {
      id: "f4",
      at: "12:18:31",
      kind: "agent",
      message: "Addressing final review note",
    },
    {
      id: "f3",
      at: "12:17:58",
      kind: "git",
      message: "Pushed immutable checkpoint",
    },
    {
      id: "f2",
      at: "12:17:22",
      kind: "tool",
      message: "Frontend suite completed in 41s",
    },
  ],
  noop: [
    {
      id: "n3",
      at: "12:18:42",
      kind: "probe",
      message: "Memory pressure false",
    },
    {
      id: "n2",
      at: "12:18:14",
      kind: "agent",
      message: "Fleet health pass completed",
    },
  ],
};
export const fixtureSnapshot: Snapshot = {
  schemaVersion: "m1.v1",
  version: 42,
  cursor: "evt-0042",
  generatedAt: "2026-08-08T18:18:42Z",
  source: "Fixture · Kubernetes + Kueue normalized",
  health: "healthy",
  session: {
    subject: "fixture-user",
    displayName: "Fixture Operator",
    initials: "FO",
    roles: ["system_admin"],
    expiresAt: null,
  },
  freshness: [
    {
      observedAt: "2026-08-08T18:18:42Z",
      source: "kubernetes",
      health: "healthy",
      message: null,
    },
  ],
  capacity: {
    availableSlots: 0,
    totalSlots: 4,
    runningJobs: 2,
    queuedJobs: 7,
    cleanupDebt: 0,
  },
  queueMeta: {
    name: "m1-light",
    policy: "BestEffortFIFO",
    quota: {
      cpuMillis: 4000,
      memoryBytes: 8589934592,
      ephemeralStorageBytes: 0,
      pids: null,
    },
    waitP50Seconds: null,
    waitP95Seconds: 4.2,
  },
  nodes: [
    {
      name: "ben1",
      roles: ["control"],
      ready: true,
      schedulable: true,
      slots: 0,
      used: 0,
      memory: "71 / 126 GiB",
      pressure: { memory: false, disk: false, pid: false },
      freshness: {
        observedAt: "2026-08-08T18:18:42Z",
        source: "metrics",
        health: "healthy",
        message: null,
      },
    },
    {
      name: "ben2",
      roles: ["agent-workloads"],
      ready: true,
      schedulable: true,
      slots: 2,
      used: 2,
      memory: "34 / 126 GiB",
      pressure: { memory: false, disk: false, pid: false },
      freshness: {
        observedAt: "2026-08-08T18:18:42Z",
        source: "metrics",
        health: "healthy",
        message: null,
      },
    },
    {
      name: "ben3",
      roles: ["agent-workloads"],
      ready: true,
      schedulable: true,
      slots: 2,
      used: 2,
      memory: "41 / 126 GiB",
      pressure: { memory: false, disk: false, pid: false },
      freshness: {
        observedAt: "2026-08-08T18:18:42Z",
        source: "metrics",
        health: "healthy",
        message: null,
      },
    },
  ],
  jobs: [
    {
      id: "worker-212",
      uid: "uid-worker-212",
      resourceVersion: "4812",
      agent: "General Worker",
      task: "Blaze modal cleanup",
      node: "ben3",
      attempt: "1 / 2",
      duration: "12m",
      cost: "$0.84",
      estimatedDuration: "18m",
      estimatedCost: "$1.21",
      active: true,
      namespace: "frontro-agent-prototype",
      syntheticM1: true,
      feed: feeds.worker,
    },
    {
      id: "noop-1042",
      uid: "uid-noop-1042",
      resourceVersion: "4814",
      agent: "M1 No-op Runner",
      task: "M1 qualification",
      node: "ben2",
      attempt: "1 / 1",
      duration: "2m",
      cost: "$0.01",
      estimatedDuration: "3m",
      estimatedCost: "$0.03",
      active: true,
      namespace: "frontro-agent-prototype",
      syntheticM1: true,
      feed: feeds.noop,
    },
  ],
  queue: [
    ["noop-1048", "M1 No-op Runner", "M1 qualification", "01:18", "prototype", "1 CPU · 2 GiB", "light", "quota reserved", "3m"],
    ["noop-1049", "M1 No-op Runner", "M1 qualification", "01:03", "prototype", "1 CPU · 2 GiB", "light", "insufficient quota", "3m"],
    ["noop-1050", "M1 No-op Runner", "M1 qualification", "00:49", "prototype", "1 CPU · 2 GiB", "light", "insufficient quota", "3m"],
    ["noop-heavy-2", "General Worker", "Production browser E2E", "00:31", "standard", "8 CPU · 24 GiB", "heavy", "flavor disabled", "24m"],
    ["worker-213", "General Worker", "Backend event refactor", "00:26", "standard", "4 CPU · 8 GiB", "standard", "capacity exhausted", "18m"],
    ["review-490", "PR Reviewer", "PR #490", "00:19", "review", "2 CPU · 4 GiB", "standard", "capacity exhausted", "7m"],
    ["monitor-burst-12", "Reliability Monitor", "Incident scan", "00:08", "high", "1 CPU · 2 GiB", "light", "quota reserved", "4m"],
  ].map((x, i) => ({
    id: x[0],
    namespace: "frontro-agent-prototype",
    agent: x[1],
    task: x[2],
    age: x[3],
    priority: x[4],
    request: x[5],
    flavor: x[6],
    reason: x[7],
    estimate: x[8],
    ageSeconds: Math.max(0, 78 - i * 12),
    position: i + 1,
  })),
  activity: [
    {
      id: "started",
      at: "12:18:40",
      tone: "success",
      title: "noop-1042 started on ben3",
      description: "The workload cleared admission, received the light flavor, and started its first attempt.",
      agent: "M1 No-op Runner",
      task: "M1 qualification",
      taskUrl: "https://app.asana.com/0/0/1217241946908788/f",
      subject: "noop-1042 · attempt 1 / 2",
      source: "Kubernetes Job event",
      duration: "1m",
      cost: "$0.01",
      timeline: timeline("Running"),
    },
    {
      id: "waiting",
      at: "12:18:31",
      tone: "warning",
      title: "noop-1048 is waiting for capacity",
      description: "All four light-work slots are occupied. The workload remains ordered and starts automatically when capacity is available.",
      agent: "M1 No-op Runner",
      task: "M1 qualification",
      subject: "noop-1048 · queued",
      source: "Kueue admission event",
      timeline: timeline("Waiting"),
    },
    {
      id: "reclaimed",
      at: "12:18:20",
      tone: "success",
      title: "noop-1037 resources reclaimed",
      description: "Job, Pod, and temporary objects were removed; no cleanup debt remains.",
      agent: "Lifecycle Janitor",
      subject: "noop-1037 · completed",
      source: "Cleanup receipt",
      duration: "7m",
      cost: "$0.02",
      timeline: timeline("Verified"),
    },
  ],
  runs: [
    {
      id: "worker-212",
      agent: "General Worker",
      task: "Blaze modal cleanup",
      state: "Running",
      node: "ben3",
      duration: "12m",
      cost: "$0.84",
      digest: "sha256:8a9d…21cf",
    },
    {
      id: "review-489-r2",
      agent: "PR Reviewer",
      task: "Hermes recursion",
      state: "Completed",
      node: "ben2",
      duration: "6m",
      cost: "$0.46",
      digest: "sha256:8a9d…21cf",
      reason: "Succeeded",
      cleanup: "12:23:14",
    },
    {
      id: "noop-1041",
      agent: "M1 No-op Runner",
      task: "Pod retry qualification",
      state: "Cleaned",
      node: "ben3",
      duration: "2m",
      cost: "$0.01",
      digest: "sha256:8a9d…21cf",
      reason: "Succeeded",
      cleanup: "Complete",
    },
  ].map((r) => ({
    ...r,
    namespace: "frontro-agent-prototype",
    attempt: 1,
    request: {
      cpuMillis: 1000,
      memoryBytes: 2147483648,
      ephemeralStorageBytes: 5368709120,
      pids: null,
    },
    peak: null,
    timeline: timeline(r.state),
  })),
  images: [],
  cleanup: [],
  qualification: [],
  platform: {
    clusterId: "fixture-cluster",
    configGitSha: "8b19a2e",
    versions: { contract: "1.0" },
    certificateExpiresAt: null,
    rollbackReady: false,
    lastVerifiedAt: null,
    authorization: "system_admin",
  },
};
